### ISSUE TITLE
Authentication-less mails

### ISSUE THREAD

**Issue by syphernl** [rohmann/wp-multisite-smtp#16]
It appears this plugin has a hard requirement for username/password authentication (since `SMTPAuth` is explicitly to `true`) but this may not work in all situations. 

It would be better if this was an option, since there may be mail relays who employ other means of validating access (e.g. IP whitelists) and wouldn't work with SMTP Auth.

**Comment by enricodeleo** [comment]
It's a fork of a fork but here https://github.com/Surbma/wp-global-smtp/pull/1 I made a pull request just for this very issue.
