### ISSUE TITLE
GLOBAL_SMTP_FROM_NAME

### ISSUE THREAD

**Issue by amjad** [rohmann/wp-multisite-smtp#22]
I have this plugin installed on a WP multi-site setup. I have not defined GLOBAL_SMTP_FROM_NAME in wp-config.php. This is causing the emails to have Network Name in the from name of the email. 

I would like to have the blog name from which the email is being sent, not the network name. How can I do that?

**Comment by bubacarrsowe** [comment]
I don't think there is a feature on this plugin to that. Sometimes ago, I got around this by using this plugin, https://wordpress.org/plugins/wp-mailfrom-ii/. It allows you to set the from email and name of subsite. You could have both installed and the whole network can use the same smtp host, username and password. Then on each subsite, you can enter the the from email and name.

**Comment by amjad** [comment]
Actually, I made it work with a [forked version](https://github.com/extremeshok/wp-multisite-smtp/blob/master/smtp.php#L33) of this plugin. Pretty simple to do!

Change Line 33 to: `$phpmailer->FromName = get_option('blogname');`

**Comment by bubacarrsowe** [comment]
Awesome, that is a neat one. Which of the SMTP global settings did you add to the wp-config file?

**Comment by amjad** [comment]
@bubacarrsowe I put all the settings as mentioned in the readme, except `GLOBAL_SMTP_FROM_NAME`. I edited my post above with some more detail.

**Comment by bubacarrsowe** [comment]
If I get you, it looks like this?
$phpmailer->FromName = get_option('blogname');

**Comment by amjad** [comment]
yes

**Comment by bubacarrsowe** [comment]
Thanks.
