### ISSUE TITLE
No option to turn off SMTP AUTH (SMTPAuth = false)

### ISSUE THREAD

**Issue by padjoo** [rohmann/wp-multisite-smtp#6]
Suggest adding GLOBAL_SMTP_AUTH_TYPE = 'NONE' option:

Line 64: 'GLOBAL_SMTP_AUTH_TYPE' => array('LOGIN','PLAIN','NTLM','NONE') );
Line 132: $phpmailer->SMTPAuth = ('NONE' != GLOBAL_SMTP_AUTH_TYPE);

**Comment by rohmann** [comment]
`GLOBAL_SMTP_SECURE` was supposed to allow "none" as an option.
