### ISSUE TITLE
GLOBAL_SMTP_DEBUG formatting

### ISSUE THREAD

**Issue by pmsteil** [rohmann/wp-multisite-smtp#7]
When I turn on GLOBAL_SMTP_DEBUG, the output I get is very difficult to read due to no <br> tags in the output.  

I looked in the code and didn't understand where the code is that is outputting this debug to try and enhance the code in this way.  

Where is all the meat of the code?  Ah, I think I get it now, you are using a built in WordPress phpMailer class - so I guess that class is responsible for the debug output?

Thanks,
Patrick

**Comment by rohmann** [comment]
Yeah, that's because it's the standard output from the PHP Mailer class. I added a few safegaurds, and now if you're testing with the [check email plugin](https://wordpress.org/plugins/check-email/) it will output an opening `<pre>` tag on the test page to help.
