### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by berndblume** [rohmann/wp-multisite-smtp#9]
Hi and thanks for the fantastic plugin.
I'm using Wordpress 4.3 Multisite.
I tried putting smtp.php under mu-plugins (that directory didn't exist, so I created it) ==> Seems to have no effect. I don't see the plugins in "Plugins", not in network admin nor in individual sites.
So I put it under plugins/wp-multisite-smtp. I was able to see it in network admin, and I was able to network activate it.
But obviously no effect. When I try the send email tool, it still uses localhost SMTP host, and does not send any email.
Also, I don't see the wp-multisite-smtp in any of the individual sites' dashboards.
What am I doing wrong?
Thanks, Bernd

**Comment by Surbma** [comment]
You have to configure the settings in wp-config.php file. Everything is described in README.md.

The file should be put back to mu-plugins folder!

**Comment by berndblume** [comment]
Hi and thanks for the quick response!
Of course I have configured all the settings in wp.config.php, as set out in README.md.
When I put smtp.php direcly into a (newly created) mu-plugins folder, wordpress doesn't function any more, I have blank screens. When I create a wp-multisite-smtp subfolder under mu-plugins, wordpress does function again, but still the plugin does not work. Am I supposed to see the plugin in the dashboards of the individual blogs? I do not see it there. I just see it in Network Admin, and I have network activated it.
Have you tested the plugin with Wordpress 4.3?
Thanks, Bernd

**Comment by Surbma** [comment]
You have to put the file in the mu-plugins folder, not any other subfolder or in the plugins folder. It activates the plugin network wide. There is no option or menu for this plugin, so you can not see anything on the dashboard.

You can enable debug mode to see, what's wrong with your installation. You can post the error message here if you don't know, what to do.

**Comment by berndblume** [comment]
I had already enabled debug mode, but I haven't seen any message.
Will the error messages appear in the wordpress GUI or in some log file?

On Sep 1, 2015, at 11:46 AM, Peter Ambrus <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to put the file in the mu-plugins folder, not any other subfolder or in the plugins folder. It activates the plugin network wide. There is no option or menu for this plugin, so you can not see anything on the dashboard.

You can enable debug mode to see, what's wrong with your installation. You can post the error message here if you don't know, what to do.

-

**Comment by Surbma** [comment]
You said, that you have a white screen. When you enable debug, there should be the error message(s).

**Comment by berndblume** [comment]
After some extensive troubleshooting, it does work now. :-)
Seems like there were a few sources of trouble:
1. The white screen seem to have resulted from having both, a network activated wp-multisite-smtp plugin in plugins/wp-multisite-smtp AND an smtp.php in mu-plugins. I network deactivated and then deleted the plugins/wp-multisite-smtp, which solved that problem. Note: The screen was absolutely blank, even though debug was enabled.
2. The send email plugin announces smtp host localhost, even though using the host specified in wp-config.php when actually sending the mail.
3. Connection via SSL for some reason did not work. I configured SSL, not TLS, in all sorts of other email clients (for that same SMTP server), and it always worked. But Wordpress couldn't connect via SSL. I tried TLS, but that failed because of the plugin's default authentication method LOGIN. I found out my SMTP server needs PLAIN instead. Changed GLOBAL_SMTP_AUTH_TYPE to PLAIN, and it finally worked!
Thanks again for your help!
Bernd

**Comment by Surbma** [comment]
I'm glad, that it is working now for you.

Which SMTP service are you using? I'm using Mandrill for years without any problem, I can highly recommend it.

**Comment by rohmann** [comment]
Hey, great to hear you got it working. As you mentioned having two copies loaded, you would have been getting a fatal PHP error for the main class already existing. Not sure why that didn't appear with WP_DEBUG enabled.

I'd like to smooth out the onboarding process a bit. If you guys have any thoughts on #10 let me know over there.
